#!/usr/bin/env python3
"""
Generate all paper figures for PQC-FL Healthcare project.

Figures produced:
  fig1_convergence.png        — FL convergence: heterogeneous vs homogeneous FL
  fig2_security_levels.png    — Security level vs latency and overhead (NIST L1/L3/L5)
  fig3_byzantine.png          — Byzantine defense: clean vs undefended vs defended
  fig4_latency_breakdown.png  — PQC vs Classical per-round latency breakdown
  fig5_dp_tradeoff.png        — Differential privacy epsilon vs AUC tradeoff
  fig6_comm_overhead.png      — Communication overhead: model payload vs crypto per round

Usage:
  python figures.py
"""

import json
import glob
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# ── Style ─────────────────────────────────────────────────────────────────────

plt.rcParams.update({
    "font.family":      "serif",
    "font.size":        11,
    "axes.titlesize":   12,
    "axes.labelsize":   11,
    "legend.fontsize":  10,
    "xtick.labelsize":  10,
    "ytick.labelsize":  10,
    "figure.dpi":       150,
    "savefig.dpi":      300,
    "savefig.bbox":     "tight",
})

BLUE   = "#2166AC"
RED    = "#D6604D"
GREEN  = "#4DAC26"
ORANGE = "#F4A582"
GRAY   = "#888888"


# ── Figure 1: FL Convergence ───────────────────────────────────────────────────

def fig1_convergence(hetero_path="results_multiseed.json",
                     pima_path="results_multiseed_pima.json"):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.5))

    # ── Left: heterogeneous federation with per-dataset AUC ──────────────────
    if os.path.exists(hetero_path):
        d = json.load(open(hetero_path))
        by_round = d["by_round"]
        rounds   = sorted(int(r) for r in by_round.keys())

        auc_mean = np.array([by_round[str(r)]["auc"]["mean"] for r in rounds])
        auc_std  = np.array([by_round[str(r)]["auc"]["std"]  for r in rounds])

        ax1.plot(rounds, auc_mean, color=BLUE, lw=2.2, label="Global AUC (mean)")
        ax1.fill_between(rounds, auc_mean - auc_std, auc_mean + auc_std,
                         color=BLUE, alpha=0.18, label="±1 std (5 seeds)")

        # per-dataset curves (only if present — generated by hetero mode)
        ds_styles = {
            "diabetes_auc": (GREEN,  "--", "Diabetes AUC"),
            "heart_auc":    (RED,    "-.", "Heart Disease AUC"),
            "cancer_auc":   (ORANGE, ":", "Breast Cancer AUC"),
        }
        for key, (col, ls, lbl) in ds_styles.items():
            if key in by_round[str(rounds[0])]:
                vals = np.array([by_round[str(r)][key]["mean"] for r in rounds])
                ax1.plot(rounds, vals, color=col, lw=1.6, ls=ls, label=lbl)

        final = auc_mean[-1]
        ax1.axhline(final, color=BLUE, lw=0.8, ls=":", alpha=0.7)
        ax1.annotate(f"Global AUC = {final:.3f}",
                     xy=(rounds[-1], final), xytext=(-5, 6),
                     textcoords="offset points", ha="right",
                     fontsize=9, color=BLUE)
    else:
        ax1.text(0.5, 0.5, "Heterogeneous results\nnot yet generated",
                 ha="center", va="center", transform=ax1.transAxes)

    ax1.set_xlabel("Communication Round")
    ax1.set_ylabel("AUC (ROC)")
    ax1.set_title("Heterogeneous FL — 5 Hospital-Specialised Nodes\n"
                  "(Diabetes · Heart Disease · Breast Cancer)")
    ax1.set_ylim(0.25, 1.0)
    ax1.legend(loc="lower right", fontsize=9)
    ax1.grid(True, alpha=0.3)

    # ── Right: homogeneous Pima ablation ─────────────────────────────────────
    if os.path.exists(pima_path):
        d = json.load(open(pima_path))
        by_round = d["by_round"]
        rounds   = sorted(int(r) for r in by_round.keys())
        auc_mean = np.array([by_round[str(r)]["auc"]["mean"] for r in rounds])
        auc_std  = np.array([by_round[str(r)]["auc"]["std"]  for r in rounds])
        acc_mean = np.array([by_round[str(r)]["accuracy"]["mean"] for r in rounds])

        ax2.plot(rounds, auc_mean, color=RED, lw=2, label="AUC (mean, 5 seeds)")
        ax2.fill_between(rounds, auc_mean - auc_std, auc_mean + auc_std,
                         color=RED, alpha=0.20, label="AUC ± 1 std")
        ax2.plot(rounds, acc_mean, color=ORANGE, lw=1.8, ls="--",
                 label="Accuracy (mean)")

        final = auc_mean[-1]
        ax2.axhline(final, color=RED, lw=0.8, ls=":", alpha=0.7)
        ax2.annotate(f"Final AUC = {final:.3f}",
                     xy=(rounds[-1], final), xytext=(-5, 6),
                     textcoords="offset points", ha="right",
                     fontsize=9, color=RED)
    else:
        ax2.text(0.5, 0.5, "Pima-only results\nnot yet generated",
                 ha="center", va="center", transform=ax2.transAxes)

    ax2.set_xlabel("Communication Round")
    ax2.set_ylabel("Metric Value")
    ax2.set_title("Homogeneous FL — 5 Diabetes Clinics\n"
                  "(Pima Indians Diabetes, non-IID by glucose quartile)")
    ax2.set_xlim(1, 50)
    ax2.set_ylim(0.25, 1.0)
    ax2.legend(loc="lower right", fontsize=9)
    ax2.grid(True, alpha=0.3)

    fig.suptitle("PQC-FL Convergence  (5 seeds × 50 rounds, PQC mode)",
                 fontsize=12, y=1.01)
    fig.tight_layout()
    fig.savefig("fig1_convergence.png")
    plt.close(fig)
    print("Saved fig1_convergence.png")


# ── Figure 2: Security Level Comparison ───────────────────────────────────────

def fig2_security_levels(path="results_security_levels_20iter_20260518_063541.json"):
    d = json.load(open(path))
    levels = d["levels"]

    labels   = [l["label"] for l in levels]
    kem_sigs = [f"{l['kem']}\n+{l['sig']}" for l in levels]

    enc_mean = np.array([l["result"]["timings"]["total_enc_ms"]["mean_ms"]   for l in levels])
    enc_std  = np.array([l["result"]["timings"]["total_enc_ms"]["std_ms"]    for l in levels])
    dec_mean = np.array([l["result"]["timings"]["total_dec_ms"]["mean_ms"]   for l in levels])
    dec_std  = np.array([l["result"]["timings"]["total_dec_ms"]["std_ms"]    for l in levels])
    rt_mean  = np.array([l["result"]["timings"]["round_trip_ms"]["mean_ms"]  for l in levels])

    overhead_kb = np.array([l["result"]["sizes"]["crypto_overhead_bytes"] / 1024 for l in levels])
    bundle_kb   = np.array([l["result"]["sizes"]["total_bundle_bytes"]    / 1024 for l in levels])
    sig_kb      = np.array([l["result"]["sizes"]["signature_bytes"]       / 1024 for l in levels])
    kem_ct_kb   = np.array([l["result"]["sizes"]["kem_ct_bytes"]          / 1024 for l in levels])

    x = np.arange(len(labels))
    width = 0.28

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4.5))

    # Left: latency
    bars_enc = ax1.bar(x - width/2, enc_mean, width, label="Encrypt + Sign",
                       color=BLUE, yerr=enc_std, capsize=4, error_kw={"lw": 1.2})
    bars_dec = ax1.bar(x + width/2, dec_mean, width, label="Decrypt + Verify",
                       color=RED, yerr=dec_std, capsize=4, error_kw={"lw": 1.2})

    for bar, val in zip(bars_enc, enc_mean):
        ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                 f"{val:.2f}", ha="center", va="bottom", fontsize=8.5)
    for bar, val in zip(bars_dec, dec_mean):
        ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                 f"{val:.2f}", ha="center", va="bottom", fontsize=8.5)

    ax1.set_xticks(x)
    ax1.set_xticklabels(kem_sigs, fontsize=9)
    ax1.set_ylabel("Latency (ms)")
    ax1.set_title("Per-Operation Latency by NIST Security Level")
    ax1.legend()
    ax1.grid(True, axis="y", alpha=0.3)
    ax1.set_ylim(0, max(enc_mean.max(), dec_mean.max()) * 1.35)

    # Right: overhead stacked bar (KEM ciphertext + signature + pubkey)
    pubkey_kb = np.array([l["result"]["sizes"]["sig_pubkey_bytes"] / 1024 for l in levels])
    nonce_kb  = 12 / 1024  # constant

    p1 = ax2.bar(x, kem_ct_kb, width*2.4, label="KEM ciphertext", color=BLUE)
    p2 = ax2.bar(x, sig_kb,    width*2.4, bottom=kem_ct_kb, label="Signature", color=RED)
    p3 = ax2.bar(x, pubkey_kb, width*2.4, bottom=kem_ct_kb + sig_kb, label="Sig public key", color=GREEN)

    total = kem_ct_kb + sig_kb + pubkey_kb
    for i, (xi, tot) in enumerate(zip(x, total)):
        ax2.text(xi, tot + 0.1, f"{tot:.1f} KB", ha="center", va="bottom", fontsize=8.5)

    ax2.set_xticks(x)
    ax2.set_xticklabels(kem_sigs, fontsize=9)
    ax2.set_ylabel("Size (KB)")
    ax2.set_title("Cryptographic Overhead per Update Bundle")
    ax2.legend(loc="upper left")
    ax2.grid(True, axis="y", alpha=0.3)
    ax2.set_ylim(0, total.max() * 1.25)

    fig.suptitle(f"Security Level Comparison  (12 KB model delta, {d['iterations']} iterations)",
                 fontsize=11, y=1.02)
    fig.tight_layout()
    fig.savefig("fig2_security_levels.png")
    plt.close(fig)
    print("Saved fig2_security_levels.png")


# ── Figure 3: Byzantine Defense ────────────────────────────────────────────────

def fig3_byzantine(multiseed_path="results_multiseed.json"):
    # Prefer multi-seed files, fall back to single-seed
    multi = sorted(glob.glob("results_byzantine_both_20r_*seeds*.json"))
    single = sorted(glob.glob("results_byzantine_both_20r_seed*.json"))
    candidates = multi if multi else single
    if not candidates:
        candidates = sorted(glob.glob("results_byzantine_both_*.json"))
    if not candidates:
        print("No Byzantine results found — skipping fig3")
        return
    byz_path = candidates[-1]
    print(f"  Using Byzantine file: {os.path.basename(byz_path)}")

    byz = json.load(open(byz_path))
    ms  = json.load(open(multiseed_path))

    n_rounds_byz = byz["rounds"]
    is_multi = "seed_results" in byz

    # Clean baseline from multiseed
    by_round = ms["by_round"]
    clean_rounds = list(range(1, n_rounds_byz + 1))
    clean_auc = np.array([by_round[str(r)]["auc"]["mean"] for r in clean_rounds
                          if str(r) in by_round])
    clean_rounds = clean_rounds[:len(clean_auc)]

    if is_multi:
        n_seeds = len(byz["seed_results"])
        seed_results = byz["seed_results"]

        # Aggregate Part A per round
        byz_rounds = list(range(1, n_rounds_byz + 1))
        a_aucs_per_round = np.array([[r["auc"] for r in sr["part_a"]["rounds"]]
                                     for sr in seed_results])
        a_det_rates = [sr["part_a"]["detection_rate"] for sr in seed_results]
        a_rate_mean = np.mean(a_det_rates)

        # Aggregate Part B per round
        b_def_per_round   = np.array([[r["auc"] for r in sr["part_b"]["with_detection"]["rounds"]]
                                      for sr in seed_results])
        b_undef_per_round = np.array([[r["auc"] for r in sr["part_b"]["without_detection"]["rounds"]]
                                      for sr in seed_results])
        b_def_aucs   = [sr["part_b"]["with_detection"]["final_auc"]    for sr in seed_results]
        b_undef_aucs = [sr["part_b"]["without_detection"]["final_auc"] for sr in seed_results]
        b_det_rates  = [sr["part_b"]["with_detection"]["detection_rate"] for sr in seed_results]
        poison_scale = seed_results[0]["part_b"]["poison_scale"]
        rogue_node   = byz["rogue_node"]
    else:
        byz_rounds    = [r["round"] for r in byz["part_b"]["without_detection"]["rounds"]]
        a_aucs_per_round = np.array([[r["auc"] for r in byz["part_a"]["rounds"]]])
        a_det_rates   = [byz["part_a"]["detection_rate"]]
        a_rate_mean   = byz["part_a"]["detection_rate"]
        b_def_per_round   = np.array([[r["auc"] for r in byz["part_b"]["with_detection"]["rounds"]]])
        b_undef_per_round = np.array([[r["auc"] for r in byz["part_b"]["without_detection"]["rounds"]]])
        b_def_aucs    = [byz["part_b"]["with_detection"]["final_auc"]]
        b_undef_aucs  = [byz["part_b"]["without_detection"]["final_auc"]]
        b_det_rates   = [byz["part_b"]["with_detection"]["detection_rate"]]
        poison_scale  = byz["part_b"]["poison_scale"]
        rogue_node    = byz["rogue_node"]
        n_seeds = 1

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.5))

    # ── Left: Part A — Signature Attack ─────────────────────────────
    a_mu = a_aucs_per_round.mean(axis=0)
    a_sd = a_aucs_per_round.std(axis=0)
    ax1.plot(byz_rounds, a_mu, color=RED, lw=2, marker="o", ms=4,
             label="AUC (sig attack active)")
    if n_seeds > 1:
        ax1.fill_between(byz_rounds, a_mu - a_sd, a_mu + a_sd, color=RED, alpha=0.2)
    ax1.plot(clean_rounds, clean_auc, color=BLUE, lw=2, ls="--",
             label="Clean baseline (no attack)")
    ax1.axvspan(1, n_rounds_byz, color=GREEN, alpha=0.05)

    seed_note = f"{n_seeds} seeds" if n_seeds > 1 else f"seed {byz.get('seed', byz.get('seeds', [42])[0])}"
    ax1.set_xlabel("Communication Round")
    ax1.set_ylabel("Global AUC")
    ax1.set_title(f"Part A — Tampered Signature Attack\n"
                  f"ML-DSA detection: {a_rate_mean*100:.0f}%  "
                  f"({n_seeds*n_rounds_byz}/{n_seeds*n_rounds_byz} rounds, {seed_note})")
    ax1.set_ylim(0.2, 1.0)
    ax1.set_xlim(1, n_rounds_byz)
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.text(0.97, 0.06,
             f"Rogue rejected\n100% of rounds",
             transform=ax1.transAxes, ha="right", va="bottom",
             fontsize=9, color=GREEN,
             bbox=dict(boxstyle="round,pad=0.3", facecolor="white", edgecolor=GREEN, alpha=0.8))

    # ── Right: Part B — Gradient Poisoning ──────────────────────────
    def_mu   = b_def_per_round.mean(axis=0)
    def_sd   = b_def_per_round.std(axis=0)
    undef_mu = b_undef_per_round.mean(axis=0)
    undef_sd = b_undef_per_round.std(axis=0)
    final_def   = np.mean(b_def_aucs)
    final_undef = np.mean(b_undef_aucs)

    ax2.plot(clean_rounds, clean_auc, color=BLUE, lw=2, ls="--",
             label="Clean baseline (no attack)")
    ax2.plot(byz_rounds, undef_mu, color=RED, lw=2, marker="s", ms=4,
             label=f"Poisoned (undefended, final={final_undef:.3f}±{np.std(b_undef_aucs):.3f})")
    ax2.plot(byz_rounds, def_mu, color=GREEN, lw=2, marker="^", ms=4,
             label=f"Defended (norm filter, final={final_def:.3f}±{np.std(b_def_aucs):.3f})")
    if n_seeds > 1:
        ax2.fill_between(byz_rounds, undef_mu - undef_sd, undef_mu + undef_sd,
                         color=RED, alpha=0.15)
        ax2.fill_between(byz_rounds, def_mu - def_sd, def_mu + def_sd,
                         color=GREEN, alpha=0.15)

    b_rate_mean = np.mean(b_det_rates)
    ax2.set_xlabel("Communication Round")
    ax2.set_ylabel("Global AUC")
    ax2.set_title(f"Part B — Gradient Poisoning  (scale={poison_scale:.0f}×)\n"
                  f"Norm-filter detection: {b_rate_mean*100:.0f}%  ({seed_note})")
    ax2.set_ylim(0.2, 1.0)
    ax2.set_xlim(1, n_rounds_byz)
    ax2.legend(loc="upper left", fontsize=9)
    ax2.grid(True, alpha=0.3)

    fig.tight_layout()
    fig.savefig("fig3_byzantine.png")
    plt.close(fig)
    print("Saved fig3_byzantine.png")


# ── Figure 4: PQC vs Classical Latency Breakdown ──────────────────────────────

def fig4_latency_breakdown():
    candidates = sorted(glob.glob("results_both_30r_*.json"))
    if not candidates:
        print("No PQC-vs-classical results found — skipping fig4")
        return
    path = candidates[-1]
    print(f"  Using comparison file: {os.path.basename(path)}")

    d = json.load(open(path))
    rd = d["rounds_detail"]
    pqc_rounds = rd["pqc"]
    cls_rounds = rd["classical"]

    rounds_x    = [r["round"] for r in pqc_rounds]
    pqc_enc     = np.array([r["avg_enc_ms"] for r in pqc_rounds])
    pqc_dec     = np.array([r["dec_ms"]     for r in pqc_rounds])
    pqc_total   = np.array([r["round_ms"]   for r in pqc_rounds])

    cls_enc     = np.array([r["avg_enc_ms"] for r in cls_rounds])
    cls_dec     = np.array([r["dec_ms"]     for r in cls_rounds])
    cls_total   = np.array([r["round_ms"]   for r in cls_rounds])

    fig, axes = plt.subplots(1, 3, figsize=(13, 4.2), sharey=False)

    def _band(ax, x, y, color, label):
        ax.plot(x, y, color=color, lw=2, label=label)
        ax.fill_between(x, y * 0.93, y * 1.07, color=color, alpha=0.15)

    # Panel 1: Encrypt time
    _band(axes[0], rounds_x, pqc_enc, BLUE,  "PQC  (ML-KEM-768 + ML-DSA-65)")
    _band(axes[0], rounds_x, cls_enc, RED,   "Classical  (RSA-4096 + HMAC)")
    axes[0].set_title("Encrypt / Sign (ms)\nper node per round")
    axes[0].set_xlabel("Round")
    axes[0].set_ylabel("Time (ms)")

    # Panel 2: Decrypt time
    _band(axes[1], rounds_x, pqc_dec, BLUE, "PQC")
    _band(axes[1], rounds_x, cls_dec, RED,  "Classical")
    axes[1].set_title("Decrypt / Verify (ms)\nserver per round")
    axes[1].set_xlabel("Round")

    # Panel 3: Total round time
    _band(axes[2], rounds_x, pqc_total, BLUE, f"PQC  (mean {pqc_total.mean():.1f} ms)")
    _band(axes[2], rounds_x, cls_total, RED,  f"Classical  (mean {cls_total.mean():.1f} ms)")
    axes[2].set_title("Total Round Latency (ms)\n(training + crypto)")
    axes[2].set_xlabel("Round")

    ratio = cls_total.mean() / pqc_total.mean()
    axes[2].text(0.97, 0.06,
                 f"PQC is {ratio:.1f}× faster\nthan RSA per round",
                 transform=axes[2].transAxes, ha="right", va="bottom",
                 fontsize=9, color=BLUE,
                 bbox=dict(boxstyle="round,pad=0.3", facecolor="white", edgecolor=BLUE, alpha=0.8))

    for ax in axes:
        ax.legend(fontsize=8.5)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(1, max(rounds_x))

    fig.suptitle("PQC vs Classical Cryptography — Per-Round Latency  (5 nodes, 30 rounds)",
                 fontsize=11)
    fig.tight_layout()
    fig.savefig("fig4_latency_breakdown.png")
    plt.close(fig)
    print("Saved fig4_latency_breakdown.png")


# ── Figure 5: Differential Privacy Tradeoff ───────────────────────────────────

def fig5_dp_tradeoff():
    # Prefer multi-seed files; fall back to single-seed
    multi = sorted(glob.glob("results_dp_sweep_*seeds*.json"))
    single = sorted(glob.glob("results_dp_sweep_30r_seed*.json"))
    candidates = multi if multi else single
    if not candidates:
        print("No DP sweep results found — skipping fig5")
        return
    path = candidates[-1]
    print(f"  Using DP file: {os.path.basename(path)}")

    d = json.load(open(path))
    n_rounds = d["rounds"]
    n_seeds  = len(d.get("seeds", [d.get("seed", 42)]))
    is_multi = "summary" in d and n_seeds > 1

    if is_multi:
        # Multi-seed: use summary for bar chart, average curves for left panel
        summary = d["summary"]
        eps_order = ["0.5", "1.0", "5.0", "10.0", "50.0", "inf"]
        eps_labels = ["0.5", "1.0", "5.0", "10.0", "50.0", "∞"]
        means = [summary[e]["mean"] for e in eps_order]
        stds  = [summary[e]["std"]  for e in eps_order]

        # Average per-round AUC across seeds per epsilon
        from collections import defaultdict
        round_aucs = defaultdict(lambda: defaultdict(list))
        for sr in d["seed_results"]:
            for r in sr["results"]:
                eps_key = r["epsilon"]
                for entry in r["rounds"]:
                    round_aucs[eps_key][entry["round"]].append(entry["auc"])
        avg_curves = {}
        for eps_key, rnd_dict in round_aucs.items():
            rounds = sorted(rnd_dict)
            avg_curves[eps_key] = (rounds,
                                   [np.mean(rnd_dict[rnd]) for rnd in rounds],
                                   [np.std(rnd_dict[rnd])  for rnd in rounds])
    else:
        results = d["results"]
        eps_order  = [r["epsilon"] for r in results]
        eps_labels = ["∞" if e == "inf" else e for e in eps_order]
        means = [r["final_auc"] for r in results]
        stds  = [0.0] * len(means)

    colors = [RED, ORANGE, "#F4D03F", GREEN, BLUE, "#7D3C98"]
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.5))

    # ── Left: mean convergence curves (± std band) ──────────────────
    for i, eps_key in enumerate(eps_order):
        lbl = f"ε = {eps_labels[i]}"
        lw  = 2.5 if eps_key == "inf" else 1.8
        ls  = "--" if eps_key == "inf" else "-"
        if is_multi:
            rds, mu, sd = avg_curves[eps_key]
            ax1.plot(rds, mu, color=colors[i], lw=lw, ls=ls, label=lbl)
            ax1.fill_between(rds,
                             [m - s for m, s in zip(mu, sd)],
                             [m + s for m, s in zip(mu, sd)],
                             color=colors[i], alpha=0.15)
        else:
            r = d["results"][i]
            rds  = [x["round"] for x in r["rounds"]]
            aucs = [x["auc"]   for x in r["rounds"]]
            ax1.plot(rds, aucs, color=colors[i], lw=lw, ls=ls, label=lbl)

    seed_note = f"{n_seeds} seeds" if n_seeds > 1 else f"seed {d.get('seed', 42)}"
    ax1.set_xlabel("Communication Round")
    ax1.set_ylabel("Global AUC")
    ax1.set_title(f"Convergence Under Differential Privacy\n"
                  f"(clip={d['dp_clip']}, δ={d['dp_delta']}, {n_rounds}r, {seed_note})")
    ax1.set_xlim(1, n_rounds)
    ax1.set_ylim(0.0, 1.0)
    ax1.legend(loc="upper left", fontsize=9)
    ax1.grid(True, alpha=0.3)

    # ── Right: final AUC bar chart with error bars ───────────────────
    x = np.arange(len(eps_labels))
    bars = ax2.bar(x, means, yerr=stds if is_multi else None,
                   color=colors, width=0.6, edgecolor="white", lw=0.8,
                   capsize=4, error_kw={"elinewidth": 1.5})

    baseline = means[-1]
    ax2.axhline(baseline, color="black", lw=1.2, ls="--", alpha=0.6,
                label=f"No-DP baseline ({baseline:.3f})")

    for bar, m, s, lbl in zip(bars, means, stds, eps_labels):
        label_txt = f"{m:.3f}" if not is_multi else f"{m:.3f}±{s:.3f}"
        ax2.text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + (s if is_multi else 0) + 0.015,
                 label_txt, ha="center", va="bottom", fontsize=8)

    ax2.set_xticks(x)
    ax2.set_xticklabels([f"ε={l}" for l in eps_labels], fontsize=10)
    ax2.set_ylabel(f"Final AUC (round {n_rounds})")
    ax2.set_title("Privacy-Utility Tradeoff\n(Final AUC by Privacy Budget ε)")
    ax2.set_ylim(0.0, 1.10)
    ax2.legend(fontsize=9)
    ax2.grid(True, axis="y", alpha=0.3)

    fig.tight_layout()
    fig.savefig("fig5_dp_tradeoff.png")
    plt.close(fig)
    print("Saved fig5_dp_tradeoff.png")


# ── Figure 6: Communication Overhead ──────────────────────────────────────────

def fig6_comm_overhead():
    candidates = sorted(glob.glob("results_both_30r_*.json"))
    if not candidates:
        print("No PQC-vs-classical results found — skipping fig6")
        return
    path = candidates[-1]
    print(f"  Using comparison file: {os.path.basename(path)}")

    d   = json.load(open(path))
    pqc = d["rounds_detail"]["pqc"]
    cls = d["rounds_detail"]["classical"]

    rounds = [r["round"] for r in pqc]

    pqc_net  = np.array([r["net_kb"]     for r in pqc])
    cls_net  = np.array([r["net_kb"]     for r in cls])
    pqc_oh   = np.array([r["overhead_b"] / 1024 for r in pqc])
    cls_oh   = np.array([r["overhead_b"] / 1024 for r in cls])
    pqc_pay  = pqc_net - pqc_oh
    cls_pay  = cls_net - cls_oh

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.5))

    # ── Left: stacked area — payload vs crypto overhead ─────────────
    ax1.stackplot(rounds, pqc_pay, pqc_oh,
                  labels=["Model weights (PQC)", "PQC crypto overhead"],
                  colors=[BLUE, RED], alpha=0.75)
    ax1.stackplot(rounds, cls_pay, cls_oh,
                  labels=["Model weights (Classical)", "Classical crypto overhead"],
                  colors=["#A8D8EA", ORANGE], alpha=0.55)

    pqc_avg = float(np.mean(pqc_net))
    cls_avg = float(np.mean(cls_net))
    ax1.axhline(pqc_avg, color=BLUE,  lw=1.2, ls="--", alpha=0.8)
    ax1.axhline(cls_avg, color=GRAY,  lw=1.2, ls="--", alpha=0.8)
    ax1.text(max(rounds)*0.98, pqc_avg + 1.5, f"PQC mean {pqc_avg:.0f} KB",
             ha="right", fontsize=8.5, color=BLUE)
    ax1.text(max(rounds)*0.98, cls_avg - 4.0, f"Classical mean {cls_avg:.0f} KB",
             ha="right", fontsize=8.5, color=GRAY)

    ax1.set_xlabel("Communication Round")
    ax1.set_ylabel("Data Transferred per Round (KB)")
    ax1.set_title("Per-Round Bandwidth: Model Payload vs Crypto Overhead\n"
                  "(5 nodes × 1 round, PQC vs Classical)")
    ax1.set_xlim(1, max(rounds))
    ax1.legend(loc="upper right", fontsize=8.5)
    ax1.grid(True, axis="y", alpha=0.3)

    # ── Right: cumulative bandwidth ──────────────────────────────────
    pqc_cumul = np.cumsum(pqc_net)
    cls_cumul = np.cumsum(cls_net)

    ax2.plot(rounds, pqc_cumul, color=BLUE, lw=2,
             label=f"PQC  (total {pqc_cumul[-1]:.0f} KB)")
    ax2.plot(rounds, cls_cumul, color=RED,  lw=2, ls="--",
             label=f"Classical  (total {cls_cumul[-1]:.0f} KB)")
    ax2.fill_between(rounds, cls_cumul, pqc_cumul,
                     color=BLUE, alpha=0.12,
                     label=f"PQC overhead  (+{pqc_cumul[-1]-cls_cumul[-1]:.0f} KB total)")

    ax2.set_xlabel("Communication Round")
    ax2.set_ylabel("Cumulative Bandwidth (KB)")
    ax2.set_title("Cumulative Bandwidth Over 30 Rounds\n"
                  f"PQC overhead: {np.mean(pqc_oh):.1f} KB/round "
                  f"({np.mean(pqc_oh)/np.mean(pqc_net)*100:.1f}% of total)")
    ax2.set_xlim(1, max(rounds))
    ax2.legend(fontsize=9)
    ax2.grid(True, alpha=0.3)

    fig.tight_layout()
    fig.savefig("fig6_comm_overhead.png")
    plt.close(fig)
    print("Saved fig6_comm_overhead.png")


# ── Main ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    print("Generating figures...\n")
    fig1_convergence()
    fig2_security_levels()
    fig3_byzantine()
    fig4_latency_breakdown()
    fig5_dp_tradeoff()
    fig6_comm_overhead()
    print("\nDone.")
